---
# Spring-Boot Profile "debug-liquibase".
# Configures the log levels to debug liquibase integration

logging:
  level:
    liquibase.: DEBUG
    org:
      springframework:
        boot:
          liquibase.*: DEBUG
