---
# Default Application Properties
server:
  port: 8080

spring:
  application:
    name: liquibase-prototype
  main:
    banner-mode: off

  datasource:
    url: jdbc:db2://localhost:50000/testdb
    username: db2inst1
    password: password
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
    # Filter the referenced changelogs and
    # apply only those changes for which the following label filter applies:
    # https://docs.liquibase.com/concepts/changelogs/attributes/labels.html
    label-filter:
      - base-product

myerpapp:
  inventory:
    enabled: false
